name: Manual Adsense Script Addition

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - name: Run Go Script
        run: go run adsense.go

      - name: Get Date
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_STATE

      - name: Check for Changes
        run: |
          git diff --exit-code || echo "CHANGES=true" >> $GITHUB_STATE

      - name: Commit and Push Changes
        if: env.CHANGES == 'true'
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Add Google Adsense script on $DATE"
          git push

      - name: Display Message if Nothing Changed
        if: env.CHANGES != 'true'
        run: echo "Nothing changed, nothing to commit"
